dev_addr: 127.0.0.1:8080
site_name: Benjamin-ASR
nav:
  - Home: index.md
  - Requirements: Requirements.md
  - Installation: Installation.md
  - Quick Start Guide: Quick-Start-Guide.md
  - Capture Audio Samples: Capture-Audio-Samples.md
  - Train Model: Train-Model.md
  - First Time Bring-up: First-Time-Bring-Up.md
  - Controlling Keyboard: Controlling-Keyboard.md
  - Controlling Mouse: Controlling-Mouse.md
  - Additional Commands: Additional-Commands.md
  - Global Shortcuts: Global-Shortcuts.md
  - Train Neural Network: Train-Neural-Network.md
  - Advanced Training: Advanced-Training.md
  - Advanced Engine Settings: Advanced-Engine-Settings.md
  - Developer: https://benjamin-int.github.io
  - About: About.md

theme: 
  name: readthedocs
  highlightjs: true
  palette:
    primary: 'indigo'
    accent: 'pink'
  favicon: 'img/favicon.ico'
  hljs_languages:
    - yaml
    - django

extra_css:
  - css/extra.css
  
markdown_extensions:
  - toc:
      permalink: ÔÉÅ
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - pymdownx.blocks.html